model: trained_models/retrosnyhesis_ReactSeq_model_on_50k_aug100.pt
src: datasets/50k_ReactSeq/test/src_test.txt
output: output/tgt_test_infer.txt
gpu: 0
beam_size: 10
n_best: 10
batch_size: 16384
#batch_size: 8192
batch_type: tokens
max_length: 500
seed: 0
