data:
  corpus_1:
    path_src: ../datasets/50k_ReactSeq/aug100_train/src_aug100_train.txt
    path_tgt: ../datasets/50k_ReactSeq/aug100_train/tgt_aug100_train.txt
  valid:
    path_src: ../datasets/50k_ReactSeq/aug20_val/src_aug20_val.txt
    path_tgt: ../datasets/50k_ReactSeq/aug20_val/tgt_aug20_val.txt

# Vocab
n_sample: 0
save_data: ../datasets/vocabs/
src_vocab: ../datasets/vocabs/whole_vocabs.src
tgt_vocab: ../datasets/vocabs/whole_vocabs.src
share_vocab: 'true'
src_seq_length: 500
tgt_seq_length: 500
overwrite: 'true'

# # Load Pretrained Model
# train_from: ../trained_models/pretrained_model_on_zinc_chembl.pt
# reset_optim: 'all'

# Log loss
tensorboard: true
tensorboard_log_dir: ../checkpoints/50k_ReactSeq_EXP2/logs

# Save Checkpoints
save_model: ../checkpoints/50k_ReactSeq_EXP2/model
save_checkpoint_steps: 10000
keep_checkpoint: 200
seed: 3435
train_steps: 2000000
valid_steps: 50000
warmup_steps: 8000
report_every: 1000

decoder_type: transformer
encoder_type: transformer
word_vec_size: 256
# rnn_size: 256
hidden_size: 256
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 1
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 1.0
max_grad_norm: 0.0

batch_size: 128
valid_batch_size: 128
batch_type: sents
normalization: sents
dropout: 0.3
attention_dropout: 0.3
label_smoothing: 0.0

max_generator_batches: 0

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

#model_dtype: fp16
# apex_opt_level: 'O1'
world_size: 1
gpu_ranks: [0]
