model: trained_models/retrosnyhesis_E_smiles_model_on_50k_aug100.pt
src: datasets/50k_e_smiles/aug20_test/src_aug20_test.txt
output: output/50k_E_smiles_aug100_train_aug20_test_infer.txt
gpu: 7
beam_size: 10
n_best: 10
batch_size: 16384
#batch_size: 8192
batch_type: tokens
max_length: 500
seed: 0

